### ISSUE TITLE
Memrise works in https now

### ISSUE THREAD

**Issue by mirkolai** [DrewSSP/bulk-audio-upload#2]
Hello,

I've been trying to use your code, but the upload returns the error code 500.
Memrise works in https now, so I simply changed the line 17

post_url = "http://www.memrise.com/ajax/thing/cell/upload_file/"

in

post_url = "https://www.memrise.com/ajax/thing/cell/upload_file/"

Thank you for your code.

**Comment by DrewSSP** [comment]
Changed and committed. Thanks!
